CREATE TABLE validaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_qr VARCHAR(255) NOT NULL,
    acceso_permitido BOOLEAN NOT NULL,
    mensaje VARCHAR(255),
    fecha_validacion TIMESTAMP(6) NOT NULL
);