spring.application.name=Preventa

server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/db_preventa?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


## Durante desarrollo permitimos la actualización automática del esquema.
# Cambiar a 'validate' o usar migraciones Flyway en producción.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true


servicio.eventos.url=http://localhost:8081/api/eventos