CREATE TABLE promotores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    codigo_promocional VARCHAR(50) UNIQUE NOT NULL,
    descuento_porcentaje DECIMAL(5,2) NOT NULL, -- Cuánto descuento se le da al cliente (ej. 10.00 %)
    comision_porcentaje DECIMAL(5,2) NOT NULL,  -- Cuánto gana el promotor por venta (ej. 5.00 %)
    estado VARCHAR(20) DEFAULT 'ACTIVO',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);