CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    id_evento BIGINT NOT NULL,
    id_ticket_generado BIGINT,
    monto_total DECIMAL(38, 2) NOT NULL,
    metodo_pago VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    fecha_venta TIMESTAMP(6) NOT NULL      
);
