spring:
  application:
    name: Tickets
  datasource:
    url: jdbc:mysql://localhost:3306/db_tickets?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

server:
  port: 8083

servicio:
  eventos:
    url: http://localhost:8081/api/eventos
